# Generated by Django 3.0.3 on 2020-02-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200227_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
